services:
  main-service-db:
    container_name: main-service-db
    image: postgres
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    expose:
      - "5432"

  main-service:
    container_name: main-service
    build:
      context: ../
      dockerfile: ./main-service/dockerfile
    depends_on:
      - main-service-db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://admin:admin@main-service-db:5432/users"
      PRIVATE_KEY_PATH: "keys/signature.pem"
      PUBLIC_KEY_PATH: "keys/signature.pub"
      POST_SERVICE_ADDR: post-service:5001
