FROM python:3.9-slim

ENV FLASK_APP=main-service.py
ENV FLASK_RUN_HOST=0.0.0.0

WORKDIR /main-service

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY main-service.py .
COPY run.sh .
COPY keys keys/.
RUN chmod +x run.sh

CMD ["sh", "run.sh"]
