services:
  post-service-db:
    container_name: post-service-db
    image: postgres
    environment:
      POSTGRES_DB: posts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    expose:
      - "5433"
    command: -p 5433

  post-service:
    container_name: post-service
    build: 
      context: ../
      dockerfile: ./post-service/dockerfile
    depends_on:
      - post-service-db
    environment:
      DATABASE_URL: "postgresql://admin:admin@post-service-db:5433/posts"
      POST_SERVICE_PORT: 5001
    expose:
      - "5001"
