FROM python:3.9-slim

WORKDIR /stat-service

# Download dependencies
COPY stat-service/requirements.txt .
RUN pip install -r requirements.txt

# Setup protofiles
RUN apt-get update && apt-get install -y protobuf-compiler
COPY proto/post-service.proto .
COPY proto/stat-service.proto .
COPY proto/compile-proto.sh .
RUN chmod +x compile-proto.sh
RUN ./compile-proto.sh

# Run service
COPY stat-service/stat-service.py .
CMD ["python3", "stat-service.py"]
