FROM python:3.9-slim

WORKDIR /stat-service

# Download dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Run service
COPY stat-service.py .
CMD ["python3", "stat-service.py"]
